points:
   key:
      padding: cy
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
   zones:
    board:
      rows:
        bottom:
        home:
        top:
      columns:
          pinkie:
             spread: cx
             rows: 
              bottom:
                bind: [0, 0, 0, 1]
                column_net: P5
              home:
                bind: [0.5, 3, 0, 1]
                column_net: P10
              top:
                bind: [0, 0, 0, 1]
                column_net: P18
          ring:
            spread: cx
            rows: 
              bottom:
                bind: [0, 0, 0, 3]
                column_net: P6
              home: 
                bind: [0,0,3,1]
                column_net: P16
              top: 
                bind: [0,3,0,1]
                column_net: P19
          middle: 
            spread: cx
            rows: 
              bottom:
                bind: [0, 3, 0, 3]
                column_net: P7
              home: 
                bind: [0,0,3,0]
                column_net: P14
              top:
                column_net: P20
                bind: [0,1,0,1]
          index: 
            spread: cx
            rows: 
              bottom:
                bind: [0, 3, 0, 0]
                column_net: P8
              home: 
                bind: [0,0,3,0]
                column_net: P15
              top: 
                bind: [0,1,3,3]
                column_net: P21
          far: 
            spread: cx
            row_overrides: 
              bottom:
                bind: [34,1, 0, 0]
                column_net: P9
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx , 1cx]
      - type: rectangle
        size: [7, 5]
        anchor:
          ref: board_index_top
          shift: [21, 6]
    cutouta:
      - type: outline
        name: raw
        fillet: 3
    cutoutb:
      - type: outline
        name: cutouta
        fillet: 1
    cutout:
      - type: outline
        name: cutoutb
        fillet: 0.5
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
pcbs:
  card:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: board_far_bottom
          shift: [0.6, cx+6.3]
          rotate: -90
        params:
          orientation: down
      pcm12:
        type: pcm12
        anchor:
          ref: board_index_top
          shift: [16.5, 6.5]
          rotate: 180
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      via3:
        type: via
        anchor: 
          ref: board_index_top
          shift: [16,3]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_index_top
          shift: [18,3]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_index_top
          shift: [23,6.5]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_index_top
          shift: [25,6.5]
        nets: 
          net: RST 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_index_top
          shift: [24.5, 9]
          rotate: 0
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_far_bottom
          shift: [0.2 , 9]
          rotate: 90
