points:
   key:
      padding: cy
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
   zones:
    board:
      rows:
        bottom:
        home:
        top:
      columns:
          pinkie:
             spread: cx
             row_overrides: 
              bottom:
                bind: [0, 0, 0, 1]
                column_net: P21
              home:
                bind: [0.5, 3, 3, 1]
                column_net: P20
          ring:
            stagger: 13
            spread: cx
            rows: 
              bottom:
                bind: [0, 0, 2, 3]
                column_net: P19
              home: 
                bind: [3,0,3,1]
                column_net: P18
              top: 
                bind: [0.5,3,0,1]
                column_net: P15
          middle: 
            stagger: 8
            spread: cx
            rows: 
              bottom:
                bind: [0, 3, 20, 3]
                column_net: P14
              home: 
                bind: [3,0,3,0]
                column_net: P16
              top:
                column_net: P10
                bind: [0.5,1,0,1]
          index: 
            stagger: -12
            spread: cx
            rows: 
              bottom:
                bind: [0, 3, 0, 0]
                column_net: P4
              home: 
                bind: [3,0,3,0]
                column_net: P5
              top: 
                bind: [0.5,1,3,3]
                column_net: P6
          far: 
            stagger: -cy - 1
            spread: cx
            rows: 
              bottom:
                bind: [3,1, 0, 73]
                column_net: P9
              home: 
                bind: [3,1,3,0]
                column_net: P7 
              top: 
                bind: [0.5,1,3,3]
                column_net: P8
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx , 1cx]
    cutout:
      - type: outline
        name: raw
        fillet: 3
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false               
pcbs:
  main:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        type: promicro
        anchor:
          ref: board_far_home
          shift: [-25, -17]
          rotate: 0
        params:
          orientation: down
      pcm12:
        type: pcm12
        anchor:
          ref: board_far_home
          shift: [-75, -22]
          rotate: 0
        nets:
          from: pos  
          to: RAW
        params:
          reverse: true 
      via3:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-2,-10]
        nets: 
          net: RAW 
      via4:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [-4,-10]
        nets: 
          net: pos 
      via5:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [8,-10]
        nets: 
          net: GND 
      via6:
        type: via
        anchor: 
          ref: board_pinkie_bottom
          shift: [6,-10]
        nets: 
          net: RST 
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST  
          r2: GND
        anchor:
          ref: board_pinkie_bottom
          shift: [7, -15]
          rotate: 0
        params:
          reverse: true 
      bat:
        type: bat
        nets: 
          neg: GND
        anchor:
          ref: board_far_bottom
          shift: [-42 , -0]
          rotate: 0
